version: '3.8'

services:
  web:
    build: .
    container_name: lablup_toy_project_web
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - APP_MODE=single-process   # Default: single-process (Can be changed to multi-process)
      - APP_WORKERS=4             # Default: 4 (Only works when APP_MODE=multi-process)
    depends_on:
      - redis

  redis:
    image: "redis:7"
    container_name: lablup_toy_project_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: